# Generated by Django 4.1 on 2022-10-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dumpling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Имя пельменя', max_length=255, verbose_name='Имя пельменя')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Пельмень',
                'verbose_name_plural': 'Пельмени',
            },
        ),
        migrations.CreateModel(
            name='DumplingMeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DumplingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DumplingTasty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('credit_card_number', models.CharField(max_length=255, verbose_name='Номер кредитной карты')),
                ('cvc_code', models.CharField(max_length=255, verbose_name='cvc-код (три цифры с обратной стороны кредитной карты)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('where_key', models.CharField(max_length=255, verbose_name='Где лежит ключ от квартиры/дома')),
                ('passport_number', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('photo', models.ImageField(default='default/128b.png', upload_to='profile_images')),
                ('bio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True, verbose_name='slug')),
                ('chort_status', models.IntegerField(default=0, verbose_name='Статус ЧОРТа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Пользователя',
                'verbose_name_plural': 'Профили Пользователей',
            },
        ),
        migrations.CreateModel(
            name='DumplingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('bad_status', models.BooleanField(default=False, verbose_name='ЧОРТ статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to=settings.AUTH_USER_MODEL)),
                ('dumpling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumpling_comments', to='dumpling.dumpling')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='comments_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='dumpling',
            name='meat',
            field=models.ForeignKey(help_text='Какое мясо в нём', on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='dumpling.dumplingmeat', verbose_name='Какое мясо в нём'),
        ),
        migrations.AddField(
            model_name='dumpling',
            name='size',
            field=models.ForeignKey(help_text='Размер пельменя', on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='dumpling.dumplingsize', verbose_name='Размер пельменя'),
        ),
        migrations.AddField(
            model_name='dumpling',
            name='tasty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='dumpling.dumplingtasty', verbose_name='Вкусный?'),
        ),
    ]
